# Generated by Django 4.2.5 on 2023-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_product_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
